import { test, expect, Page } from '@playwright/test';
import { AppPage } from './pages/AppPage';

/**
 * Real-browser Phase 1 exit-criteria verification for the shared German Exam
 * Engine's Hören adapter, against telc C1 Hochschule content generated by
 * the REAL deployed pipeline (real OpenAI, real Supabase, real Qwen/TTS) —
 * nothing here mocks /api/ai/german-exam/generate or /api/ai/tts-batch.
 * Requires E2E_EMAIL / E2E_PASSWORD for an account whose profile has
 * german_test='telc', german_level='C1 Hochschule', and an active
 * subscription (or profiles.status='affiliate') so generation isn't
 * blocked by the paywall. Generation takes 10-30s per part — timeouts are
 * sized generously.
 *
 * NOT covered here (documented, not silently skipped): TTS-failure
 * simulation and generation-500 simulation would need route interception
 * of the REAL upstream, which risks corrupting a real in-flight generation
 * call's billing/state — left as a follow-up with mocked routes instead.
 */

type NetEvent = { url: string; method: string; startedAt: number; finishedAt?: number; status?: number };

function instrumentNetwork(page: Page) {
  const events: NetEvent[] = [];
  const byRequest = new Map<unknown, NetEvent>();
  page.on('request', req => {
    const url = req.url();
    if (!url.includes('/api/ai/')) return;
    const ev: NetEvent = { url, method: req.method(), startedAt: Date.now() };
    events.push(ev);
    byRequest.set(req, ev);
  });
  page.on('requestfinished', async req => {
    const ev = byRequest.get(req);
    if (!ev) return;
    ev.finishedAt = Date.now();
    try { ev.status = (await req.response())?.status(); } catch { /* ignore */ }
  });
  return events;
}

function countMatching(events: NetEvent[], needle: string): NetEvent[] {
  return events.filter(e => e.url.includes(needle));
}

/**
 * Full real-form login, bypassing the shared setup project's storageState
 * fast path entirely. Supabase rotates the refresh token on every use, so
 * the SAME static tests/e2e/.auth/user.json (written once by auth.setup.ts)
 * is only valid for the FIRST test that consumes it — every subsequent test
 * in this file gets a fresh context loading that same now-stale token and
 * fails to restore a session. Since this spec (unlike the single-test
 * 21-hoeren-listening.spec.ts) runs many independent tests against the same
 * account, each one logs in for real instead of depending on a shared
 * snapshot. The "Sign in" -> modal transition is also given a couple of
 * retries — an animation/mount timing flake independent of auth state.
 */
async function realLogin(page: Page): Promise<void> {
  const email = process.env.E2E_EMAIL || '';
  const password = process.env.E2E_PASSWORD || '';
  expect(email && password, 'E2E_EMAIL/E2E_PASSWORD must be set to a telc C1 Hochschule + affiliate/subscribed test account').toBeTruthy();

  await page.context().clearCookies();
  await page.goto('/', { waitUntil: 'domcontentloaded' });

  const loginBtn = page.locator(
    '#nlNavSignIn, [data-i18n="nav.signIn"], [data-i18n="landing_nav_login"], #landingLoginBtn, button:has-text("Login"), button:has-text("Sign in")'
  ).first();

  let modalOpen = false;
  for (let attempt = 0; attempt < 3 && !modalOpen; attempt++) {
    await loginBtn.waitFor({ state: 'visible', timeout: 10_000 }).catch(() => {});
    await loginBtn.click().catch(() => {});
    modalOpen = await page.locator('#authEmail').waitFor({ state: 'visible', timeout: 8_000 }).then(() => true).catch(() => false);
  }
  expect(modalOpen, 'sign-in modal never opened after retries').toBeTruthy();

  await page.locator('#authEmail').fill(email);
  await page.locator('#authPassword').fill(password);
  await page.locator('#authSubmit').click();

  await page.waitForFunction(
    () => sessionStorage.getItem('ss_logged_in') === 'true' ||
      !!document.querySelector('#courseAddBtn') ||
      !!document.querySelector('#sdCourseList') ||
      !!document.querySelector('#welcomeState') ||
      !!document.querySelector('#courseOverview'),
    { timeout: 30_000 }
  );
}

async function loginAsTelcLearner(page: Page): Promise<AppPage> {
  const app = new AppPage(page);
  await realLogin(page);
  await page.evaluate(() => {
    const w = window as unknown as { _userType?: string; _applyUserTypeUI?: () => void };
    w._userType = 'learner';
    if (typeof w._applyUserTypeUI === 'function') w._applyUserTypeUI();
  });
  return app;
}

async function openHoeren(page: Page, app: AppPage) {
  await app.navigateTo('chatbot');
  const listenPanelLink = page.locator('[data-testid="german-panel-listening"]');
  await expect(listenPanelLink).toBeVisible();
  await listenPanelLink.click();
  await expect(page.locator('#glListeningView')).toBeVisible();
}

test.describe('German Exam Engine — Hören, real generated content (live)', () => {
  test.describe.configure({ mode: 'serial' });

  test('HV1 loads via the generated path, exactly 1 generate + 1 tts-batch call, matching UI works', async ({ page }) => {
    test.setTimeout(150_000);
    const events = instrumentNetwork(page);
    const app = await loginAsTelcLearner(page);
    await openHoeren(page, app);

    // Generated path (not the static LISTEN_SETS fallback): the part
    // switcher only ever shows when ls.usingGenerated is true.
    const switcher = page.locator('#glListenPartSwitcher');
    await expect(switcher).toBeVisible({ timeout: 60_000 });
    await expect(page.locator('#glListenPartHV1')).toHaveClass(/active/);

    // Content actually loaded (not stuck on the "Generating…" placeholder).
    await expect(page.locator('.gl-listen-generating')).toHaveCount(0, { timeout: 60_000 });
    await expect(page.locator('#glListenTaskPanel .gl-listen-option').first()).toBeVisible({ timeout: 30_000 });

    // Network call counts — the actual point of this test.
    const generateCalls = countMatching(events, '/api/ai/german-exam/generate');
    const ttsCalls = countMatching(events, '/api/ai/tts-batch');
    expect(generateCalls.length, `generate calls: ${JSON.stringify(generateCalls)}`).toBe(1);
    expect(ttsCalls.length, `tts-batch calls: ${JSON.stringify(ttsCalls)}`).toBe(1);
    // Ordering: generate must fully finish before tts-batch starts (content
    // is frozen before the frontend ever calls TTS).
    expect(generateCalls[0].finishedAt!).toBeLessThanOrEqual(ttsCalls[0].startedAt);

    // HV1 speaker-matching interaction: 9 options per item (8 speakers + "None").
    const options = page.locator('#glListenTaskPanel .gl-listen-option');
    const optCount = await options.count();
    expect(optCount).toBe(9);

    // Answer Q1, observe result (don't need to control correctness — proves
    // the renderer/grader round-trip works either way).
    await options.first().click();
    await page.click('#glListenCheckBtn');
    await expect(page.locator('.gl-listen-feedback-title')).toBeVisible();

    // Walk through remaining questions, exercising hint / replay / transcript
    // on different items so results persistence (next test) sees a mix.
    // "Unanswered" is detected via isEnabled(), not isVisible() — a resolved
    // option button stays VISIBLE (just disabled), so isVisible() alone
    // would misread an already-answered question as still-open and hang
    // retrying a click against a disabled element.
    for (let i = 1; i < 12; i++) {
      const nextBtn = page.locator('#glListenNextQBtn');
      if (!(await nextBtn.isVisible().catch(() => false))) break;
      const label = await nextBtn.innerText();
      await nextBtn.click();

      const firstOption = page.locator('#glListenTaskPanel .gl-listen-option').first();
      const unanswered = await firstOption.isEnabled().catch(() => false);
      if (unanswered) {
        if (i === 2) {
          await page.click('#glListenHintBtn').catch(() => {});
        }
        await firstOption.click();
        await page.click('#glListenCheckBtn');
        const retryBtn = page.locator('#glListenRetryBtn');
        if (await retryBtn.isVisible().catch(() => false)) {
          if (i === 3) {
            const replayBtn = page.locator('#glListenReplayEvidenceBtn');
            if (await replayBtn.isVisible().catch(() => false)) await replayBtn.click();
          }
          await retryBtn.click();
          await page.locator('#glListenTaskPanel .gl-listen-option').nth(1).click();
          await page.click('#glListenCheckBtn');
        }
        const transcriptBtn = page.locator('#glListenTranscriptBtn');
        if (await transcriptBtn.isVisible().catch(() => false)) await transcriptBtn.click();
      }
      if (label === 'Finish') break;
    }

    await expect(page.locator('#glListenEnd')).toBeVisible({ timeout: 10_000 });
    await expect(page.locator('.gl-listen-end-score')).toBeVisible();

    // Still exactly one generate + one tts-batch call for this whole part —
    // answering/hinting/replaying must never re-trigger either.
    expect(countMatching(events, '/api/ai/german-exam/generate').length).toBe(1);
    expect(countMatching(events, '/api/ai/tts-batch').length).toBe(1);
  });

  test('HV2 is reachable from the part switcher: 10 items, exactly 3 options each, no state leakage between items', async ({ page }) => {
    test.setTimeout(150_000);
    const app = await loginAsTelcLearner(page);
    await openHoeren(page, app);
    await expect(page.locator('#glListenPartSwitcher')).toBeVisible({ timeout: 60_000 });

    await page.click('#glListenPartHV2');
    await expect(page.locator('.gl-listen-generating')).toHaveCount(0, { timeout: 90_000 });
    await expect(page.locator('#glListenPartHV2')).toHaveClass(/active/);

    const debug = await page.evaluate(() => (window as unknown as { _glListenDebugState: () => { partId: string; currentTaskType: string; questionCount: number } })._glListenDebugState());
    expect(debug.partId).toBe('hv2');
    expect(debug.currentTaskType).toBe('sentence_completion_mc3');
    expect(debug.questionCount).toBe(10); // official telc structure: 10 items

    const options = page.locator('#glListenTaskPanel .gl-listen-option');
    await expect(options).toHaveCount(3); // exactly 3 continuations per item

    // Select option B on item 1, then move to item 2 without answering (Next
    // is disabled until Check, so answer minimally) and confirm no residual
    // "gl-selected" class survives onto a fresh, unrelated set of buttons.
    await options.nth(1).click();
    await expect(options.nth(1)).toHaveClass(/gl-selected/);
    await page.click('#glListenCheckBtn');
    await expect(page.locator('.gl-listen-feedback-title')).toBeVisible();
    await page.click('#glListenNextQBtn');

    const item2Options = page.locator('#glListenTaskPanel .gl-listen-option');
    await expect(item2Options).toHaveCount(3);
    const leaked = await item2Options.evaluateAll(els => els.some(el => el.classList.contains('gl-selected')));
    expect(leaked, 'a fresh item must not inherit the previous item\'s selected-option styling').toBe(false);
  });

  test('HV3 is reachable from the part switcher: note-completion fields, typing works, layout holds up under long content', async ({ page }) => {
    test.setTimeout(150_000);
    const app = await loginAsTelcLearner(page);
    await openHoeren(page, app);
    await expect(page.locator('#glListenPartSwitcher')).toBeVisible({ timeout: 60_000 });

    await page.click('#glListenPartHV3');
    await expect(page.locator('.gl-listen-generating')).toHaveCount(0, { timeout: 90_000 });
    await expect(page.locator('#glListenPartHV3')).toHaveClass(/active/);

    const debug = await page.evaluate(() => (window as unknown as { _glListenDebugState: () => { partId: string; currentTaskType: string; questionCount: number } })._glListenDebugState());
    expect(debug.partId).toBe('hv3');
    expect(debug.currentTaskType).toBe('structured_note_completion');
    expect(debug.questionCount).toBe(10); // 10 note-completion fields across the session

    // Long generated lecture transcript must not blow out page width — the
    // Hören workspace column should stay within the viewport.
    const workspaceBox = await page.locator('#glListenWorkspace').boundingBox();
    const viewport = page.viewportSize();
    expect(workspaceBox, 'workspace must be measurable').not.toBeNull();
    if (workspaceBox && viewport) {
      expect(workspaceBox.width).toBeLessThanOrEqual(viewport.width + 2); // +2px rounding slack
    }
    const hasHorizontalOverflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth + 2);
    expect(hasHorizontalOverflow, 'long HV3 content must not cause horizontal page overflow').toBe(false);

    const noteInput = page.locator('#glListenNoteInput');
    await expect(noteInput).toBeVisible();
    await noteInput.fill('Testantwort für die Notiz');
    await expect(noteInput).toHaveValue('Testantwort für die Notiz');
    await page.click('#glListenCheckBtn');
    await expect(page.locator('.gl-listen-feedback-title')).toBeVisible();
  });

  test('Practice weak areas: results save finishes before the next generate call fires', async ({ page }) => {
    test.setTimeout(150_000);
    const events = instrumentNetwork(page);
    const app = await loginAsTelcLearner(page);
    await openHoeren(page, app);
    await expect(page.locator('.gl-listen-generating')).toHaveCount(0, { timeout: 60_000 });

    // Race through the session quickly (don't care about correctness here).
    // Snapshot isVisible() checks are deliberately followed by a short
    // settle wait — the option/next-button DOM is rebuilt on every render,
    // and a raw isVisible().catch(()=>false) taken mid-rebuild can read as
    // "gone" for one frame even though it reappears immediately after.
    for (let i = 0; i < 12; i++) {
      const opts = page.locator('#glListenTaskPanel .gl-listen-option');
      if (await opts.first().count() > 0 && await opts.first().isEnabled().catch(() => false)) {
        await opts.first().click();
        await page.click('#glListenCheckBtn');
        await page.waitForTimeout(150);
        const retryBtn = page.locator('#glListenRetryBtn');
        if (await retryBtn.count() > 0) {
          await retryBtn.click();
          await page.waitForTimeout(150);
          await page.locator('#glListenTaskPanel .gl-listen-option').nth(1).click();
          await page.click('#glListenCheckBtn');
          await page.waitForTimeout(150);
        }
      }
      const nextBtn = page.locator('#glListenNextQBtn');
      if (await nextBtn.count() === 0) break;
      const label = await nextBtn.innerText();
      await nextBtn.click();
      await page.waitForTimeout(150);
      if (label === 'Finish') break;
    }
    await expect(page.locator('#glListenEnd')).toBeVisible({ timeout: 10_000 });

    const preClickDebug = await page.evaluate(() => (window as unknown as { _glListenDebugState: () => { attemptsBufferLength: number; answeredCount: number } })._glListenDebugState());
    expect(preClickDebug.answeredCount, `expected all 10 questions answered, got ${preClickDebug.answeredCount}`).toBe(10);
    expect(preClickDebug.attemptsBufferLength, 'expected one buffered attempt per answered question').toBe(10);

    const weakBtn = page.locator('#glListenWeakBtn');
    const hasWeak = await weakBtn.isVisible().catch(() => false);
    test.skip(!hasWeak, 'No weak categories this run (all answers happened to be correct) — nothing to race.');

    // Ordering proof via Playwright's own request/response promises directly
    // (not the hand-rolled `events` array, whose requestfinished-derived
    // timestamps can lag a beat behind the page's already-awaited fetch) —
    // both timestamps below are captured locally, in this script, the
    // instant each promise resolves, removing any dependency on Playwright's
    // internal event delivery timing.
    const resultsResponsePromise = page.waitForResponse(
      resp => resp.url().includes('/api/ai/german-exam/results') && resp.request().method() === 'POST',
      { timeout: 60_000 }
    );
    const regenerateRequestPromise = page.waitForRequest(
      req => req.url().includes('/api/ai/german-exam/generate') && req.method() === 'POST',
      { timeout: 90_000 }
    );

    await weakBtn.click();
    await resultsResponsePromise;
    const resultsFinishedAt = Date.now();
    await regenerateRequestPromise;
    const regenerateStartedAt = Date.now();

    await expect(page.locator('#glListenPractice')).toBeVisible({ timeout: 60_000 });
    await expect(page.locator('#glListenEnd')).toBeHidden();

    expect(regenerateStartedAt, 'regenerate request must not start before the results save finished')
      .toBeGreaterThanOrEqual(resultsFinishedAt);

    // Sanity cross-check against the broader instrumentation: some
    // results/generate calls did happen after the click (exact count not
    // asserted here — that's HV1's job — this test is about ordering).
    expect(countMatching(events, '/api/ai/german-exam/results').length).toBeGreaterThanOrEqual(1);
    expect(countMatching(events, '/api/ai/german-exam/generate').length).toBeGreaterThanOrEqual(1);
  });

  test('rapid part switching: HV1 -> HV2 -> HV3 without waiting, final state is HV3, stale responses do not win', async ({ page }) => {
    test.setTimeout(150_000);
    const events = instrumentNetwork(page);
    const app = await loginAsTelcLearner(page);
    await openHoeren(page, app);
    await expect(page.locator('#glListenPartSwitcher')).toBeVisible({ timeout: 60_000 });

    // Don't wait for HV1 to finish generating — immediately request HV2,
    // then immediately HV3. This is the exact scenario lsGenerateOrLoadPart's
    // ls._genRequestToken guard exists for.
    await page.click('#glListenPartHV2');
    await page.click('#glListenPartHV3');

    // Let all three in-flight requests settle.
    await expect(page.locator('.gl-listen-generating')).toHaveCount(0, { timeout: 90_000 });
    await page.waitForTimeout(1000); // let any last-arriving stale response's .then() run, if it were going to

    // Final visible state must be HV3: the part switcher shows HV3 active,
    // and the task panel shows HV3's structured_note_completion input, not
    // HV1's speaker-matching options or HV2's mc3 radios.
    await expect(page.locator('#glListenPartHV3')).toHaveClass(/active/);
    await expect(page.locator('#glListenPartHV1')).not.toHaveClass(/active/);
    await expect(page.locator('#glListenPartHV2')).not.toHaveClass(/active/);
    const noteInput = page.locator('#glListenNoteInput');
    await expect(noteInput).toBeVisible({ timeout: 5000 });

    // Not just the visible title/class — the INTERNAL state (which part is
    // loaded, and what task type the current question actually is) must
    // also be HV3. A title/class can visibly say the right thing while a
    // stale response's data survived underneath it; this catches that.
    const debug = await page.evaluate(() => (window as unknown as { _glListenDebugState: () => { partId: string; currentTaskType: string; usingGenerated: boolean } })._glListenDebugState());
    expect(debug.usingGenerated).toBe(true);
    expect(debug.partId).toBe('hv3');
    expect(debug.currentTaskType).toBe('structured_note_completion');

    // All three generate calls were issued (nothing was silently skipped),
    // even though only the last one's result was ever applied to the DOM.
    const genCalls = countMatching(events, '/api/ai/german-exam/generate');
    expect(genCalls.length).toBeGreaterThanOrEqual(2); // at least HV2 + HV3; HV1's may or may not have started in time
  });

  test('navigating away invalidates a pending generation request', async ({ page }) => {
    test.setTimeout(150_000);
    const events = instrumentNetwork(page);
    const app = await loginAsTelcLearner(page);
    await openHoeren(page, app);
    await expect(page.locator('#glListenPartSwitcher')).toBeVisible({ timeout: 60_000 });

    // Leave almost immediately, before HV1's generate call can possibly
    // resolve (real generation takes 10-30s).
    await page.locator('[data-testid="chatbot-nav-home"]').click();
    await expect(page.locator('#glListeningView')).toBeHidden();

    // Give the in-flight HV1 request time to actually finish server-side.
    await page.waitForTimeout(20_000);

    // Re-enter Hören: this issues a fresh generate call and its own fresh
    // token. The late-arriving original response must not have repainted
    // anything while we were away, and must not clobber this new load.
    await page.locator('[data-testid="german-panel-listening"]').click();
    await expect(page.locator('#glListeningView')).toBeVisible();
    await expect(page.locator('.gl-listen-generating')).toHaveCount(0, { timeout: 90_000 });

    const debug = await page.evaluate(() => (window as unknown as { _glListenDebugState: () => { partId: string; usingGenerated: boolean; questionCount: number } })._glListenDebugState());
    expect(debug.usingGenerated).toBe(true);
    expect(debug.partId).toBe('hv1');
    expect(debug.questionCount).toBe(10);
    // At least two generate calls total (the abandoned one + the fresh one
    // on re-entry) — proves leaving didn't somehow suppress the re-entry
    // call, and the abandoned one's lingering .then() (if it fired at all
    // after this point) did not visibly break anything.
    expect(countMatching(events, '/api/ai/german-exam/generate').length).toBeGreaterThanOrEqual(1);
  });

  test('navigating away stops audio; returning to Hören does not auto-resume it', async ({ page }) => {
    test.setTimeout(120_000);
    const app = await loginAsTelcLearner(page);
    await openHoeren(page, app);
    await expect(page.locator('.gl-listen-generating')).toHaveCount(0, { timeout: 60_000 });
    await expect(page.locator('#glListenPlayBtn')).toBeEnabled({ timeout: 30_000 });

    await page.click('#glListenPlayBtn');
    await expect(page.locator('#glListenPlayBtn')).toHaveAttribute('aria-label', 'Pause audio', { timeout: 15_000 });

    await page.locator('[data-testid="chatbot-nav-home"]').click();
    await expect(page.locator('#glListeningView')).toBeHidden();

    await page.locator('[data-testid="german-panel-listening"]').click();
    await expect(page.locator('#glListeningView')).toBeVisible();
    await page.waitForTimeout(500);
    await expect(page.locator('#glListenPlayBtn')).toHaveAttribute('aria-label', 'Play audio');
  });
});
