import { test, expect, Page } from '@playwright/test';
import { AppPage } from './pages/AppPage';

/**
 * Real-browser Phase 1 exit-criteria verification for the shared German Exam
 * Engine's Hören adapter, against telc C1 Hochschule content generated by
 * the REAL deployed pipeline (real OpenAI, real Supabase, real Qwen/TTS) —
 * nothing here mocks /api/ai/german-exam/generate or /api/ai/tts-batch.
 * Requires E2E_EMAIL / E2E_PASSWORD for an account whose profile has
 * german_test='telc', german_level='C1 Hochschule', and an active
 * subscription (or profiles.status='affiliate') so generation isn't
 * blocked by the paywall. Generation takes 10-30s per part — timeouts are
 * sized generously.
 *
 * NOT covered here (documented, not silently skipped): TTS-failure
 * simulation and generation-500 simulation would need route interception
 * of the REAL upstream, which risks corrupting a real in-flight generation
 * call's billing/state — left as a follow-up with mocked routes instead.
 */

type NetEvent = { url: string; method: string; startedAt: number; finishedAt?: number; status?: number };

function instrumentNetwork(page: Page) {
  const events: NetEvent[] = [];
  const byRequest = new Map<unknown, NetEvent>();
  page.on('request', req => {
    const url = req.url();
    if (!url.includes('/api/ai/')) return;
    const ev: NetEvent = { url, method: req.method(), startedAt: Date.now() };
    events.push(ev);
    byRequest.set(req, ev);
  });
  page.on('requestfinished', async req => {
    const ev = byRequest.get(req);
    if (!ev) return;
    ev.finishedAt = Date.now();
    try { ev.status = (await req.response())?.status(); } catch { /* ignore */ }
  });
  return events;
}

function countMatching(events: NetEvent[], needle: string): NetEvent[] {
  return events.filter(e => e.url.includes(needle));
}

async function loginAsTelcLearner(page: Page): Promise<AppPage> {
  const app = new AppPage(page);
  await app.goto();
  const ok = await app.loginIfNeeded();
  expect(ok, 'E2E_EMAIL/E2E_PASSWORD must be set to a telc C1 Hochschule + affiliate/subscribed test account').toBeTruthy();
  await page.evaluate(() => {
    const w = window as unknown as { _userType?: string; _applyUserTypeUI?: () => void };
    w._userType = 'learner';
    if (typeof w._applyUserTypeUI === 'function') w._applyUserTypeUI();
  });
  return app;
}

async function openHoeren(page: Page, app: AppPage) {
  await app.navigateTo('chatbot');
  const listenPanelLink = page.locator('[data-testid="german-panel-listening"]');
  await expect(listenPanelLink).toBeVisible();
  await listenPanelLink.click();
  await expect(page.locator('#glListeningView')).toBeVisible();
}

test.describe('German Exam Engine — Hören, real generated content (live)', () => {
  test.describe.configure({ mode: 'serial' });

  test('HV1 loads via the generated path, exactly 1 generate + 1 tts-batch call, matching UI works', async ({ page }) => {
    test.setTimeout(150_000);
    const events = instrumentNetwork(page);
    const app = await loginAsTelcLearner(page);
    await openHoeren(page, app);

    // Generated path (not the static LISTEN_SETS fallback): the part
    // switcher only ever shows when ls.usingGenerated is true.
    const switcher = page.locator('#glListenPartSwitcher');
    await expect(switcher).toBeVisible({ timeout: 60_000 });
    await expect(page.locator('#glListenPartHV1')).toHaveClass(/active/);

    // Content actually loaded (not stuck on the "Generating…" placeholder).
    await expect(page.locator('.gl-listen-generating')).toHaveCount(0, { timeout: 60_000 });
    await expect(page.locator('#glListenTaskPanel .gl-listen-option').first()).toBeVisible({ timeout: 30_000 });

    // Network call counts — the actual point of this test.
    const generateCalls = countMatching(events, '/api/ai/german-exam/generate');
    const ttsCalls = countMatching(events, '/api/ai/tts-batch');
    expect(generateCalls.length, `generate calls: ${JSON.stringify(generateCalls)}`).toBe(1);
    expect(ttsCalls.length, `tts-batch calls: ${JSON.stringify(ttsCalls)}`).toBe(1);
    // Ordering: generate must fully finish before tts-batch starts (content
    // is frozen before the frontend ever calls TTS).
    expect(generateCalls[0].finishedAt!).toBeLessThanOrEqual(ttsCalls[0].startedAt);

    // HV1 speaker-matching interaction: 9 options per item (8 speakers + "None").
    const options = page.locator('#glListenTaskPanel .gl-listen-option');
    const optCount = await options.count();
    expect(optCount).toBe(9);

    // Q1: answer, observe result (don't need to control correctness —
    // proves the renderer/grader round-trip works either way).
    await options.first().click();
    await page.click('#glListenCheckBtn');
    await expect(page.locator('.gl-listen-feedback-title')).toBeVisible();

    // Walk through remaining questions, exercising hint / replay / transcript
    // on different items so results persistence (next test) sees a mix.
    for (let i = 0; i < 12; i++) {
      const nextBtn = page.locator('#glListenNextQBtn');
      const stillOnQuestion = await page.locator('#glListenTaskPanel .gl-listen-option').first().isVisible().catch(() => false);
      if (stillOnQuestion) {
        // Not yet answered this question — use assistance sometimes.
        if (i === 1) {
          await page.click('#glListenHintBtn').catch(() => {});
        }
        const opts = page.locator('#glListenTaskPanel .gl-listen-option');
        await opts.first().click();
        await page.click('#glListenCheckBtn');
        const retryBtn = page.locator('#glListenRetryBtn');
        if (await retryBtn.isVisible().catch(() => false)) {
          if (i === 2) {
            const replayBtn = page.locator('#glListenReplayEvidenceBtn');
            if (await replayBtn.isVisible().catch(() => false)) await replayBtn.click();
          }
          await retryBtn.click();
          const opts2 = page.locator('#glListenTaskPanel .gl-listen-option');
          await opts2.nth(1).click();
          await page.click('#glListenCheckBtn');
        }
        const transcriptBtn = page.locator('#glListenTranscriptBtn');
        if (await transcriptBtn.isVisible().catch(() => false)) await transcriptBtn.click();
      }
      if (!(await nextBtn.isVisible().catch(() => false))) break;
      const label = await nextBtn.innerText();
      await nextBtn.click();
      if (label === 'Finish') break;
    }

    await expect(page.locator('#glListenEnd')).toBeVisible({ timeout: 10_000 });
    await expect(page.locator('.gl-listen-end-score')).toBeVisible();

    // Still exactly one generate + one tts-batch call for this whole part —
    // answering/hinting/replaying must never re-trigger either.
    expect(countMatching(events, '/api/ai/german-exam/generate').length).toBe(1);
    expect(countMatching(events, '/api/ai/tts-batch').length).toBe(1);
  });

  test('Practice weak areas: results save finishes before the next generate call fires', async ({ page }) => {
    test.setTimeout(150_000);
    const events = instrumentNetwork(page);
    const app = await loginAsTelcLearner(page);
    await openHoeren(page, app);
    await expect(page.locator('.gl-listen-generating')).toHaveCount(0, { timeout: 60_000 });

    // Race through the session quickly (don't care about correctness here).
    for (let i = 0; i < 12; i++) {
      const opts = page.locator('#glListenTaskPanel .gl-listen-option');
      if (await opts.first().isVisible().catch(() => false)) {
        await opts.first().click();
        await page.click('#glListenCheckBtn');
        const retryBtn = page.locator('#glListenRetryBtn');
        if (await retryBtn.isVisible().catch(() => false)) {
          await retryBtn.click();
          await page.locator('#glListenTaskPanel .gl-listen-option').nth(1).click();
          await page.click('#glListenCheckBtn');
        }
      }
      const nextBtn = page.locator('#glListenNextQBtn');
      if (!(await nextBtn.isVisible().catch(() => false))) break;
      const label = await nextBtn.innerText();
      await nextBtn.click();
      if (label === 'Finish') break;
    }
    await expect(page.locator('#glListenEnd')).toBeVisible({ timeout: 10_000 });

    const weakBtn = page.locator('#glListenWeakBtn');
    const hasWeak = await weakBtn.isVisible().catch(() => false);
    test.skip(!hasWeak, 'No weak categories this run (all answers happened to be correct) — nothing to race.');

    const beforeClick = Date.now();
    await weakBtn.click();
    await expect(page.locator('#glListenPractice')).toBeVisible({ timeout: 60_000 });
    await expect(page.locator('#glListenEnd')).toBeHidden();

    const resultsCalls = countMatching(events, '/api/ai/german-exam/results').filter(e => e.startedAt >= beforeClick - 5000);
    const genCallsAfterClick = countMatching(events, '/api/ai/german-exam/generate').filter(e => e.startedAt >= beforeClick);
    expect(resultsCalls.length, 'expected a results POST from the weak-retry flow').toBeGreaterThanOrEqual(1);
    expect(genCallsAfterClick.length, 'expected a regenerate call after weak-retry').toBeGreaterThanOrEqual(1);

    const resultsFinish = resultsCalls[0].finishedAt;
    const regenStart = genCallsAfterClick[0].startedAt;
    expect(resultsFinish, 'results call never finished').toBeDefined();
    expect(regenStart).toBeGreaterThanOrEqual(resultsFinish!);
  });

  test('rapid part switching: HV1 -> HV2 -> HV3 without waiting, final state is HV3, stale responses do not win', async ({ page }) => {
    test.setTimeout(150_000);
    const events = instrumentNetwork(page);
    const app = await loginAsTelcLearner(page);
    await openHoeren(page, app);
    await expect(page.locator('#glListenPartSwitcher')).toBeVisible({ timeout: 60_000 });

    // Don't wait for HV1 to finish generating — immediately request HV2,
    // then immediately HV3. This is the exact scenario lsGenerateOrLoadPart's
    // ls._genRequestToken guard exists for.
    await page.click('#glListenPartHV2');
    await page.click('#glListenPartHV3');

    // Let all three in-flight requests settle.
    await expect(page.locator('.gl-listen-generating')).toHaveCount(0, { timeout: 90_000 });
    await page.waitForTimeout(1000); // let any last-arriving stale response's .then() run, if it were going to

    // Final visible state must be HV3: the part switcher shows HV3 active,
    // and the task panel shows HV3's structured_note_completion input, not
    // HV1's speaker-matching options or HV2's mc3 radios.
    await expect(page.locator('#glListenPartHV3')).toHaveClass(/active/);
    await expect(page.locator('#glListenPartHV1')).not.toHaveClass(/active/);
    await expect(page.locator('#glListenPartHV2')).not.toHaveClass(/active/);
    const noteInput = page.locator('#glListenNoteInput');
    await expect(noteInput).toBeVisible({ timeout: 5000 });

    // All three generate calls were issued (nothing was silently skipped),
    // even though only the last one's result was ever applied to the DOM.
    const genCalls = countMatching(events, '/api/ai/german-exam/generate');
    expect(genCalls.length).toBeGreaterThanOrEqual(2); // at least HV2 + HV3; HV1's may or may not have started in time
  });

  test('navigating away stops audio; returning to Hören does not auto-resume it', async ({ page }) => {
    test.setTimeout(120_000);
    const app = await loginAsTelcLearner(page);
    await openHoeren(page, app);
    await expect(page.locator('.gl-listen-generating')).toHaveCount(0, { timeout: 60_000 });
    await expect(page.locator('#glListenPlayBtn')).toBeEnabled({ timeout: 30_000 });

    await page.click('#glListenPlayBtn');
    await expect(page.locator('#glListenPlayBtn')).toHaveAttribute('aria-label', 'Pause audio', { timeout: 15_000 });

    await page.locator('[data-testid="chatbot-nav-home"]').click();
    await expect(page.locator('#glListeningView')).toBeHidden();

    await page.locator('[data-testid="german-panel-listening"]').click();
    await expect(page.locator('#glListeningView')).toBeVisible();
    await page.waitForTimeout(500);
    await expect(page.locator('#glListenPlayBtn')).toHaveAttribute('aria-label', 'Play audio');
  });
});
