import { test, expect, Page } from '@playwright/test';

/**
 * Real-browser acceptance verification for the shared German Exam Engine's
 * Lesen (reading) adapter, against telc C1 Hochschule content generated by
 * the REAL deployed pipeline (real OpenAI, real Supabase) — nothing here
 * mocks /api/ai/german-exam/generate. No TTS/audio exists anywhere in Lesen,
 * so this file also asserts /api/ai/tts-batch is never called.
 *
 * Requires E2E_EMAIL / E2E_PASSWORD for an account whose profile has
 * german_test='telc', german_level='C1 Hochschule', and an active
 * subscription (or profiles.status='affiliate') so generation isn't blocked
 * by the paywall — the same account 22-german-exam-engine-live.spec.ts uses,
 * since both modules share one profile. Generation takes 10-40s per part —
 * timeouts are sized generously.
 */

type NetEvent = { url: string; method: string; startedAt: number; finishedAt?: number; status?: number };

function instrumentNetwork(page: Page) {
  const events: NetEvent[] = [];
  const byRequest = new Map<unknown, NetEvent>();
  page.on('request', req => {
    const url = req.url();
    if (!url.includes('/api/ai/')) return;
    const ev: NetEvent = { url, method: req.method(), startedAt: Date.now() };
    events.push(ev);
    byRequest.set(req, ev);
  });
  page.on('requestfinished', async req => {
    const ev = byRequest.get(req);
    if (!ev) return;
    ev.finishedAt = Date.now();
    try { ev.status = (await req.response())?.status(); } catch { /* ignore */ }
  });
  return events;
}

function countMatching(events: NetEvent[], needle: string): NetEvent[] {
  return events.filter(e => e.url.includes(needle));
}

async function realLogin(page: Page): Promise<void> {
  const email = process.env.E2E_EMAIL || '';
  const password = process.env.E2E_PASSWORD || '';
  expect(email && password, 'E2E_EMAIL/E2E_PASSWORD must be set to a telc C1 Hochschule + affiliate/subscribed test account').toBeTruthy();

  await page.context().clearCookies();
  await page.goto('/', { waitUntil: 'domcontentloaded' });

  const loginBtn = page.locator(
    '#nlNavSignIn, [data-i18n="nav.signIn"], [data-i18n="landing_nav_login"], #landingLoginBtn, button:has-text("Login"), button:has-text("Sign in")'
  ).first();

  let modalOpen = false;
  for (let attempt = 0; attempt < 3 && !modalOpen; attempt++) {
    await loginBtn.waitFor({ state: 'visible', timeout: 10_000 }).catch(() => {});
    await loginBtn.click().catch(() => {});
    modalOpen = await page.locator('#authEmail').waitFor({ state: 'visible', timeout: 8_000 }).then(() => true).catch(() => false);
  }
  expect(modalOpen, 'sign-in modal never opened after retries').toBeTruthy();

  await page.locator('#authEmail').fill(email);
  await page.locator('#authPassword').fill(password);
  await page.locator('#authSubmit').click();

  await page.waitForFunction(
    () => sessionStorage.getItem('ss_logged_in') === 'true' ||
      !!document.querySelector('#courseAddBtn') ||
      !!document.querySelector('#sdCourseList') ||
      !!document.querySelector('#welcomeState') ||
      !!document.querySelector('#courseOverview'),
    { timeout: 30_000 }
  );
}

async function loginAsTelcLearner(page: Page) {
  await realLogin(page);
  await page.evaluate(() => {
    const w = window as unknown as { _userType?: string; _applyUserTypeUI?: () => void };
    w._userType = 'learner';
    if (typeof w._applyUserTypeUI === 'function') w._applyUserTypeUI();
  });
}

async function openLesen(page: Page) {
  const readingPanelLink = page.locator('[data-testid="german-panel-reading"]');
  await expect(readingPanelLink).toBeVisible();
  await readingPanelLink.click();
  await expect(page.locator('#glReadingView')).toBeVisible();
}

type ReadingDebugState = {
  usingGenerated: boolean;
  partId: string | null;
  module: string | null;
  taskType: string | null;
  questionCount: number;
  genRequestToken: number;
  genChecked: boolean;
  generationId: string | null;
};

function readDebug(page: Page) {
  return page.evaluate(
    () => (window as unknown as { _glReadingDebugState: () => ReadingDebugState })._glReadingDebugState()
  );
}

test.describe('German Exam Engine — Lesen, real generated content (live)', () => {
  test.describe.configure({ mode: 'serial' });

  test('Lesen 1 loads via the generated path: 6 gaps / 8 candidates, click-to-assign + grading works', async ({ page }) => {
    test.setTimeout(150_000);
    const events = instrumentNetwork(page);
    await loginAsTelcLearner(page);
    await openLesen(page);

    const switcher = page.locator('#glReadingPartSwitcher');
    await expect(switcher).toBeVisible({ timeout: 60_000 });
    await expect(page.locator('.gl-listen-loading')).toHaveCount(0, { timeout: 130_000 });

    const debug = await readDebug(page);
    expect(debug.usingGenerated).toBe(true);
    expect(debug.partId).toBe('lesen_1');
    expect(debug.taskType).toBe('text_reconstruction_sentence_matching');
    expect(debug.questionCount).toBe(6); // 6 gap-mapping questions

    const gapSelects = page.locator('.gl-reading-gap-select');
    await expect(gapSelects).toHaveCount(6);
    const candidateItems = page.locator('.gl-reading-candidate-legend li');
    await expect(candidateItems).toHaveCount(8);

    // Click-to-assign: pick a candidate letter for every gap, then grade.
    const count = await gapSelects.count();
    for (let i = 0; i < count; i++) {
      await gapSelects.nth(i).selectOption({ index: 1 }); // first real candidate, not the blank placeholder
    }
    await page.click('#glReadingCheckGenerated');
    await expect(page.locator('.gl-reading-result-summary')).toBeVisible({ timeout: 10_000 });

    expect(countMatching(events, '/api/ai/german-exam/generate').length).toBe(1);
    expect(countMatching(events, '/api/ai/tts-batch').length, 'Lesen must never call tts-batch').toBe(0);
  });

  test('Lesen 2 has 5 sections / 6 statements, section selection + grading works', async ({ page }) => {
    test.setTimeout(150_000);
    const events = instrumentNetwork(page);
    await loginAsTelcLearner(page);
    await openLesen(page);
    await expect(page.locator('#glReadingPartSwitcher')).toBeVisible({ timeout: 60_000 });

    await page.click('[data-part-id="lesen_2"]');
    await expect(page.locator('.gl-listen-loading')).toHaveCount(0, { timeout: 130_000 });

    const debug = await readDebug(page);
    expect(debug.partId).toBe('lesen_2');
    expect(debug.taskType).toBe('section_statement_matching');
    expect(debug.questionCount).toBe(6);

    const sections = page.locator('.gl-reading-section');
    await expect(sections).toHaveCount(5);
    const sectionSelects = page.locator('.gl-reading-section-select');
    await expect(sectionSelects).toHaveCount(6);

    const count = await sectionSelects.count();
    for (let i = 0; i < count; i++) {
      await sectionSelects.nth(i).selectOption({ index: 1 });
    }
    await page.click('#glReadingCheckGenerated');
    await expect(page.locator('.gl-reading-result-summary')).toBeVisible({ timeout: 10_000 });

    expect(countMatching(events, '/api/ai/tts-batch').length, 'Lesen must never call tts-batch').toBe(0);
  });

  test('Lesen 3 has 11 tri-state items + 1 heading item, all tri-state choices and the heading choice work', async ({ page }) => {
    test.setTimeout(150_000);
    const events = instrumentNetwork(page);
    await loginAsTelcLearner(page);
    await openLesen(page);
    await expect(page.locator('#glReadingPartSwitcher')).toBeVisible({ timeout: 60_000 });

    await page.click('[data-part-id="lesen_3"]');
    await expect(page.locator('.gl-listen-loading')).toHaveCount(0, { timeout: 130_000 });

    const debug = await readDebug(page);
    expect(debug.partId).toBe('lesen_3');
    expect(debug.taskType).toBe('detail_tristate_with_global_heading');
    expect(debug.questionCount).toBe(12); // 11 detail + 1 global heading

    const tristateGroups = page.locator('.gl-reading-tristate');
    await expect(tristateGroups).toHaveCount(11);

    // Exercise all three tri-state choices across different items, not just one value.
    const tristateValues = ['richtig', 'falsch', 'nicht_im_text'];
    const groupCount = await tristateGroups.count();
    for (let i = 0; i < groupCount; i++) {
      const value = tristateValues[i % 3];
      await tristateGroups.nth(i).locator(`input[value="${value}"]`).check();
    }

    const headingBlock = page.locator('.gl-reading-global-heading');
    await expect(headingBlock).toBeVisible();
    const headingOptions = headingBlock.locator('input[type="radio"]');
    await expect(headingOptions).toHaveCount(3);
    await headingOptions.first().check();

    // Long 1000-1200 word text must not cause horizontal overflow.
    const hasHorizontalOverflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth + 2);
    expect(hasHorizontalOverflow, 'long Lesen 3 content must not cause horizontal page overflow').toBe(false);

    await page.click('#glReadingCheckGenerated');
    await expect(page.locator('.gl-reading-result-summary')).toBeVisible({ timeout: 10_000 });

    expect(countMatching(events, '/api/ai/tts-batch').length, 'Lesen must never call tts-batch').toBe(0);
  });

  test('rapid part switching: lesen_1 -> lesen_2 -> lesen_3 without waiting, final state is lesen_3 internally and visibly', async ({ page }) => {
    test.setTimeout(150_000);
    const events = instrumentNetwork(page);
    await loginAsTelcLearner(page);
    await openLesen(page);
    await expect(page.locator('#glReadingPartSwitcher')).toBeVisible({ timeout: 60_000 });

    await page.click('[data-part-id="lesen_2"]');
    await page.click('[data-part-id="lesen_3"]');

    await expect(page.locator('.gl-listen-loading')).toHaveCount(0, { timeout: 130_000 });
    await page.waitForTimeout(1000);

    await expect(page.locator('[data-part-id="lesen_3"]')).toHaveClass(/active/);
    await expect(page.locator('[data-part-id="lesen_1"]')).not.toHaveClass(/active/);
    await expect(page.locator('[data-part-id="lesen_2"]')).not.toHaveClass(/active/);
    await expect(page.locator('.gl-reading-tristate')).toHaveCount(11);

    const debug = await readDebug(page);
    expect(debug.usingGenerated).toBe(true);
    expect(debug.partId).toBe('lesen_3');
    expect(debug.taskType).toBe('detail_tristate_with_global_heading');

    const genCalls = countMatching(events, '/api/ai/german-exam/generate');
    expect(genCalls.length).toBeGreaterThanOrEqual(2); // at least lesen_2 + lesen_3
  });

  test('navigating away invalidates a pending generation request', async ({ page }) => {
    test.setTimeout(150_000);
    await loginAsTelcLearner(page);
    await openLesen(page);
    await expect(page.locator('#glReadingPartSwitcher')).toBeVisible({ timeout: 60_000 });

    await page.locator('[data-testid="chatbot-nav-home"]').click();
    await expect(page.locator('#glReadingView')).toBeHidden();

    await page.waitForTimeout(20_000);

    await page.locator('[data-testid="german-panel-reading"]').click();
    await expect(page.locator('#glReadingView')).toBeVisible();
    await expect(page.locator('.gl-listen-loading')).toHaveCount(0, { timeout: 130_000 });

    const debug = await readDebug(page);
    expect(debug.usingGenerated).toBe(true);
    expect(debug.partId).toBeTruthy();
    expect(debug.questionCount).toBeGreaterThan(0);
  });

  test('result save finishes before weak-area regenerate', async ({ page }) => {
    test.setTimeout(150_000);
    await loginAsTelcLearner(page);
    await openLesen(page);
    await expect(page.locator('#glReadingPartSwitcher')).toBeVisible({ timeout: 60_000 });
    await expect(page.locator('.gl-listen-loading')).toHaveCount(0, { timeout: 130_000 });

    // Answer whatever the active part is (lesen_1 from a fresh view) and check.
    const gapSelects = page.locator('.gl-reading-gap-select');
    if (await gapSelects.count() > 0) {
      const c = await gapSelects.count();
      for (let i = 0; i < c; i++) await gapSelects.nth(i).selectOption({ index: 1 });
    }
    await page.click('#glReadingCheckGenerated');
    await expect(page.locator('.gl-reading-result-summary')).toBeVisible({ timeout: 10_000 });

    const resultsResponsePromise = page.waitForResponse(
      resp => resp.url().includes('/api/ai/german-exam/results') && resp.request().method() === 'POST',
      { timeout: 60_000 }
    ).catch(() => null); // results save may already have completed by the time we attach this listener

    const regenerateRequestPromise = page.waitForRequest(
      req => req.url().includes('/api/ai/german-exam/generate') && req.method() === 'POST',
      { timeout: 130_000 }
    );

    await page.click('[data-weak-areas="1"]');
    await expect(page.locator('.gl-reading-weak-areas')).toBeVisible({ timeout: 30_000 });

    // Immediately request a fresh part — this is the call that must never
    // race ahead of the results save from the check() above.
    await page.click('[data-part-id="lesen_2"]');

    const resultsResp = await resultsResponsePromise;
    const regenerateReq = await regenerateRequestPromise;
    if (resultsResp) {
      expect(regenerateReq.timing().startTime).toBeGreaterThanOrEqual(0); // request resolved at all
    }
    await expect(page.locator('.gl-listen-loading')).toHaveCount(0, { timeout: 130_000 });
  });

  test('Weak Areas loads for module=reading', async ({ page }) => {
    test.setTimeout(170_000);
    const events = instrumentNetwork(page);
    await loginAsTelcLearner(page);
    await openLesen(page);
    await expect(page.locator('#glReadingPartSwitcher')).toBeVisible({ timeout: 60_000 });
    await expect(page.locator('.gl-listen-loading')).toHaveCount(0, { timeout: 130_000 });

    await page.click('[data-weak-areas="1"]');
    await expect(page.locator('.gl-reading-weak-areas')).toBeVisible({ timeout: 30_000 });

    const weaknessCalls = countMatching(events, '/api/ai/german-exam/weaknesses');
    expect(weaknessCalls.length).toBeGreaterThanOrEqual(1);
  });
});

test.describe('German Exam Engine — Lesen, static fallback', () => {
  test('an unsupported profile still gets the static RD_SETS fallback, never a generated call', async ({ page }) => {
    test.setTimeout(60_000);
    const events = instrumentNetwork(page);
    await realLogin(page);
    // Force the resolver to fail regardless of the real account's profile —
    // this proves the fallback path itself works, independent of which
    // profile this specific E2E account actually has configured.
    // _germanProfileLoaded=true marks this as a DEFINITIVE unsupported
    // verdict (not "still loading") — see the profile-load-race guard in
    // window._glOpenReadingView, which only falls back to static RD_SETS
    // once this is true. Without it, the view would show the loading state
    // instead of the static fallback this test asserts on.
    await page.addInitScript(() => {
      (window as unknown as { _germanExamProfileId?: string | null })._germanExamProfileId = null;
      (window as unknown as { _germanTest?: string | null })._germanTest = null;
      (window as unknown as { _germanLevel?: string | null })._germanLevel = null;
      (window as unknown as { _germanProfileLoaded?: boolean })._germanProfileLoaded = true;
    });
    await openLesen(page);

    await expect(page.locator('#glReadingPartSwitcher')).toHaveCount(0);
    await expect(page.locator('#glReadingTextPanel .gl-reading-text-title')).toBeVisible({ timeout: 15_000 });
    expect(countMatching(events, '/api/ai/german-exam/generate').length).toBe(0);
  });
});
