create table if not exists public.ai_chat_conversations (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_conversation_id text not null,
  course_id text,
  active_document_id uuid references public.documents(id) on delete set null,
  title text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, client_conversation_id)
);

create table if not exists public.ai_chat_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.ai_chat_conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_message_id text not null,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now(),
  unique (conversation_id, client_message_id)
);

create index if not exists ai_chat_conversations_user_updated_idx
  on public.ai_chat_conversations (user_id, updated_at desc);
create index if not exists ai_chat_messages_conversation_idx
  on public.ai_chat_messages (conversation_id, created_at);

alter table public.ai_chat_conversations enable row level security;
alter table public.ai_chat_messages enable row level security;

drop policy if exists "users manage own ai conversations" on public.ai_chat_conversations;
create policy "users manage own ai conversations"
  on public.ai_chat_conversations for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "users manage own ai messages" on public.ai_chat_messages;
create policy "users manage own ai messages"
  on public.ai_chat_messages for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

grant select, insert, update, delete on public.ai_chat_conversations to authenticated, service_role;
grant select, insert, update, delete on public.ai_chat_messages to authenticated, service_role;
grant usage, select on sequence public.ai_chat_messages_id_seq to authenticated, service_role;
