"""Hand-authored DSH golden content for the OFFLINE qualification suite.

Written by hand (not generated by any model) so the gates can be tested with known-good and deliberately
broken content. This is test fixture material only: it is not exam content, is never served to learners and
is not claimed to be exam-quality. Lengths follow MPO 2025 §10(4) (HV 5,500-7,000 chars, LV 4,500-6,000).
"""

from __future__ import annotations

import copy

from app.services.german_exams.dsh_content_model import source_fingerprint

# ---- LV text (topic lv_circular_economy) ----------------------------------------------------------
S_LINEAR = ("Während in der linearen Wirtschaft Produkte hergestellt, verkauft und nach kurzer Nutzung entsorgt werden, "
            "versucht die Kreislaufwirtschaft, Materialien so lange wie möglich im Umlauf zu halten.")
S_PRICES = ("Dieser Ansatz ist keineswegs neu, doch erst die gestiegenen Preise für Energie und Metalle haben ihm in den "
            "vergangenen Jahren eine breitere Aufmerksamkeit verschafft.")
S_REPAIR = "Die Reparatur von Geräten wird von den Herstellern häufig erschwert."
S_REUSE = "Durch die Wiederverwendung von Bauteilen kann der Bedarf an neuem Material erheblich gesenkt werden."
S_INVEST = "Weil die Preise für Rohstoffe gestiegen sind, investieren viele Unternehmen in Recyclingverfahren."
S_ROLE = "Die gemeinsame Nutzung von Gütern, etwa durch Verleihsysteme, spielt in der Praxis bisher nur eine untergeordnete Rolle."

LV_PARAGRAPHS = [
    "Die Kreislaufwirtschaft gilt in der aktuellen Debatte über Ressourcenschonung als ein Modell, das den Verbrauch von "
    "Rohstoffen und die Entstehung von Abfall grundlegend verändern soll. " + S_LINEAR + " " + S_PRICES,
    "Ein zentraler Baustein des Modells ist die Gestaltung langlebiger Produkte. Geräte, die sich öffnen, reparieren und "
    "aufrüsten lassen, müssen seltener ersetzt werden als solche, deren Gehäuse verklebt und deren Akkus fest verbaut sind. "
    + S_REPAIR + " Kritiker sehen darin eine bewusste Strategie, denn ein defektes Produkt führt in vielen Fällen zu einem "
    "Neukauf. Verbraucherverbände fordern deshalb ein gesetzlich verankertes Recht auf Reparatur, das Hersteller verpflichten "
    "würde, Ersatzteile und Anleitungen über Jahre hinaus bereitzuhalten.",
    S_REUSE + " Besonders im Bauwesen, das für einen großen Teil des Abfallaufkommens verantwortlich ist, gewinnt dieser "
    "Gedanke an Bedeutung. Türen, Fenster und Stahlträger aus abgerissenen Gebäuden werden zunehmend aufbereitet und in neuen "
    "Projekten eingesetzt, anstatt zerkleinert und deponiert zu werden. Allerdings erfordert dieses Vorgehen eine sorgfältige "
    "Dokumentation der verwendeten Materialien, die bei älteren Gebäuden oft fehlt.",
    S_INVEST + " Ein Beispiel dafür ist die Rückgewinnung seltener Metalle aus Elektronikschrott, die in Smartphones und "
    "Batterien verarbeitet werden. Während die Gewinnung aus Erzen mit hohem Energieaufwand und erheblichen Umweltschäden "
    "verbunden ist, verursacht das Recycling deutlich geringere Belastungen. Dennoch bleibt die Wirtschaftlichkeit dieser "
    "Verfahren stark von den Weltmarktpreisen abhängig: Sinken die Preise, verliert das Recycling seinen finanziellen Anreiz.",
    "Skeptiker weisen darauf hin, dass die Kreislaufwirtschaft an physikalische und ökonomische Grenzen stößt. Kein "
    "Recyclingprozess arbeitet völlig verlustfrei; bei jedem Durchlauf geht ein Teil des Materials verloren oder verliert an "
    "Qualität. Hinzu kommt der sogenannte Rebound-Effekt: Wenn Produkte günstiger und umweltfreundlicher werden, steigt "
    "häufig der Konsum, sodass die erzielten Einsparungen teilweise wieder aufgezehrt werden. " + S_ROLE,
    "Ein Blick auf die Textilbranche zeigt, wie groß die Herausforderung ist. Jedes Jahr werden weltweit Millionen Tonnen "
    "Kleidung produziert, von denen ein erheblicher Teil nach wenigen Monaten aussortiert wird. Zwar existieren "
    "Sammelsysteme, doch lassen sich Mischgewebe bisher nur schwer in ihre Fasern zerlegen. Einige Hersteller experimentieren "
    "deshalb mit Kleidungsstücken aus nur einem Material, die sich später leichter verwerten lassen, und mit Mietmodellen, "
    "bei denen die Kundschaft die Ware nach der Nutzung zurückgibt.",
    "Auch im Umgang mit Lebensmitteln spielt der Gedanke des Kreislaufs eine Rolle. Bioabfälle aus Haushalten und Gaststätten "
    "können zu Kompost oder Biogas verarbeitet werden und liefern so Dünger und Energie. Voraussetzung ist allerdings, dass "
    "die Abfälle sauber getrennt gesammelt werden, was in dicht bebauten Städten mit wenig Platz für zusätzliche Tonnen nicht "
    "immer gelingt. Zudem lehnen manche Bürgerinnen und Bürger die Getrenntsammlung ab, weil sie zusätzlichen Aufwand und "
    "Geruchsbelästigung befürchten.",
    "Politisch wird die Kreislaufwirtschaft inzwischen auf mehreren Ebenen gefördert. Die Europäische Union hat Vorgaben zur "
    "Recyclingquote von Verpackungen eingeführt und diskutiert verbindliche Regeln für die Haltbarkeit von Elektrogeräten. Auf "
    "kommunaler Ebene entstehen Reparaturcafés und Tauschbörsen, die von Freiwilligen getragen werden. Ob diese Initiativen "
    "ausreichen, um den Rohstoffverbrauch spürbar zu senken, ist unter Fachleuten umstritten.",
    "Der Autor kommt zu dem Schluss, dass die Kreislaufwirtschaft kein Allheilmittel, wohl aber ein notwendiger Bestandteil "
    "einer nachhaltigen Wirtschaftspolitik ist. Sie könne den Verbrauch von Ressourcen verringern, wenn Produkte langlebig "
    "gestaltet, Reparaturen erleichtert und Recyclingverfahren wirtschaftlich attraktiv gemacht würden. Entscheidend sei "
    "jedoch, dass sie durch eine Verringerung des Konsums ergänzt und nicht als Rechtfertigung für unveränderte "
    "Kaufgewohnheiten missbraucht werde.",
]
LV_TEXT = "\n\n".join(LV_PARAGRAPHS)
LV_SOURCE_ID = "golden-lv-1"


def _span(sentence: str) -> dict[str, int]:
    start = LV_TEXT.index(sentence)
    return {"start": start, "end": start + len(sentence)}


def _pt(pid: str, desc: str, points: int, *stems: str) -> dict:
    return {"pointId": pid, "description": desc, "points": points, "alternatives": list(stems)}


LV_CONTENT = {
    "sourceId": LV_SOURCE_ID,
    "source": {"text": LV_TEXT},
    "tasks": [
        {"form": "questions", "items": [
            {"itemId": "lv_q1", "question": "Worin unterscheidet sich die Kreislaufwirtschaft von der linearen Wirtschaft?",
             "maxPoints": 2,
             "requiredPoints": [
                 _pt("lv_q1_p1", "Lineare Wirtschaft: herstellen, verkaufen, nach kurzer Nutzung entsorgen", 1, "entsorg", "weggeworfen"),
                 _pt("lv_q1_p2", "Kreislaufwirtschaft: Materialien möglichst lange im Umlauf halten", 1, "im umlauf", "lange genutzt")],
             "referenceAnswer": "In der linearen Wirtschaft werden Produkte nach kurzer Nutzung entsorgt, in der Kreislaufwirtschaft "
                                "bleiben die Materialien möglichst lange im Umlauf.",
             "errorfulVariant": "In lineare Wirtschaft Produkte wird nach kurz Nutzung entsorgen, in Kreislaufwirtschaft Materialien "
                                "bleiben möglichst lang im Umlauf."},
            {"itemId": "lv_q2", "question": "Warum hat das Modell in den letzten Jahren mehr Aufmerksamkeit erhalten?",
             "maxPoints": 2,
             "requiredPoints": [
                 _pt("lv_q2_p1", "Die Preise für Energie und Metalle sind gestiegen", 2, "preise", "teurer")],
             "referenceAnswer": "Weil die Preise für Energie und Metalle gestiegen sind.",
             "errorfulVariant": "Weil Preise von Energie und Metall sind gestiegen."},
        ]},
        {"form": "summary", "items": [
            {"itemId": "lv_sum", "question": "Fassen Sie die Position des Autors zusammen.", "maxPoints": 3,
             "requiredPoints": [
                 _pt("lv_sum_p1", "Kein Allheilmittel, aber notwendiger Bestandteil nachhaltiger Wirtschaftspolitik", 1, "allheilmittel", "notwendig"),
                 _pt("lv_sum_p2", "Wirkt nur mit langlebigen Produkten, leichterer Reparatur und attraktivem Recycling", 1, "langleb", "reparatur"),
                 _pt("lv_sum_p3", "Muss durch weniger Konsum ergänzt werden", 1, "konsum")],
             "referenceAnswer": "Der Autor hält die Kreislaufwirtschaft für kein Allheilmittel, aber für notwendig; sie wirkt nur mit "
                                "langlebigen Produkten und leichterer Reparatur, und sie muss durch weniger Konsum ergänzt werden.",
             "errorfulVariant": "Autor meint Kreislaufwirtschaft kein Allheilmittel aber notwendig, sie wirken mit langlebig Produkte und "
                                "Reparatur, und Konsum weniger ergänzen muss."},
        ]},
    ],
}


def _fam(fid: str, *accepted: str) -> dict:
    return {"familyId": fid, "accepted": list(accepted)}


WS_CONTENT = {
    "sourceRef": {"sourceId": LV_SOURCE_ID, "sha256": source_fingerprint(LV_TEXT)},
    "items": [
        {"itemId": "ws_1", "form": "completion", "category": "morphological", "maxPoints": 1,
         "prompt": "Ergänzen Sie das passende Nomen zu „wieder verwenden“: Durch die ____ von Bauteilen kann der Bedarf an neuem "
                   "Material erheblich gesenkt werden.",
         "sourceSpan": _span(S_REUSE), "sourceSentence": S_REUSE,
         "families": [_fam("reuse", "Wiederverwendung"), _fam("continued_use", "Weiterverwendung")]},
        {"itemId": "ws_2", "form": "transformation", "category": "syntactic", "maxPoints": 2,
         "prompt": "Formulieren Sie den Satz mit „aufgrund“ um: Weil die Preise für Rohstoffe gestiegen sind, investieren viele "
                   "Unternehmen in Recyclingverfahren.",
         "sourceSpan": _span(S_INVEST), "sourceSentence": S_INVEST,
         "families": [
             _fam("aufgrund_phrase", "Aufgrund der gestiegenen Preise für Rohstoffe investieren viele Unternehmen in Recyclingverfahren."),
             _fam("aufgrund_compound", "Aufgrund gestiegener Rohstoffpreise investieren viele Unternehmen in Recyclingverfahren.")]},
        {"itemId": "ws_3", "form": "transformation", "category": "syntactic", "maxPoints": 2,
         "prompt": "Formen Sie den Satz ins Aktiv um: Die Reparatur von Geräten wird von den Herstellern häufig erschwert.",
         "sourceSpan": _span(S_REPAIR), "sourceSentence": S_REPAIR,
         "families": [
             _fam("active_regular", "Die Hersteller erschweren die Reparatur von Geräten häufig."),
             _fam("active_fronted", "Häufig erschweren die Hersteller die Reparatur von Geräten.")]},
        {"itemId": "ws_4", "form": "completion", "category": "idiomatic", "maxPoints": 1,
         "prompt": "Ergänzen Sie den Ausdruck: Die gemeinsame Nutzung von Gütern, etwa durch Verleihsysteme, spielt in der Praxis "
                   "bisher nur eine untergeordnete ____.",
         "sourceSpan": _span(S_ROLE), "sourceSentence": S_ROLE,
         "families": [_fam("role", "Rolle")]},
    ],
}

# What a competent blind solver answers for each WS item (used by the fake solver).
WS_SOLVER_ANSWERS = {
    "ws_1": "Wiederverwendung",
    "ws_2": "Aufgrund gestiegener Rohstoffpreise investieren viele Unternehmen in Recyclingverfahren.",
    "ws_3": "Häufig erschweren die Hersteller die Reparatur von Geräten.",
    "ws_4": "Rolle",
}

# ---- HV lecture (topic hv_sleep_learning) ----------------------------------------------------------
HV_PARAGRAPHS = [
    "Guten Morgen, meine Damen und Herren, und herzlich willkommen zur heutigen Vorlesung. Ich möchte mit Ihnen heute über ein "
    "Thema sprechen, das jeden von Ihnen betrifft, das im Studienalltag aber erstaunlich oft vernachlässigt wird: den "
    "Zusammenhang zwischen Schlaf und Lernleistung. Zunächst werde ich kurz erklären, wie der Schlaf aufgebaut ist. Danach "
    "stelle ich Ihnen zwei Untersuchungen vor, die den Einfluss des Schlafs auf das Gedächtnis belegen. Zum Schluss gebe ich "
    "Ihnen einige praktische Empfehlungen für die Prüfungsvorbereitung.",
    "Beginnen wir mit dem Aufbau des Schlafs. Viele Menschen stellen sich den Schlaf als einen gleichförmigen Zustand vor, in "
    "dem der Körper und das Gehirn einfach ausruhen. Das ist ein Irrtum. Tatsächlich durchläuft ein Erwachsener in einer "
    "Nacht vier- bis sechsmal einen Zyklus, der ungefähr neunzig Minuten dauert und aus drei Phasen besteht. Die erste Phase "
    "ist der Leichtschlaf. In dieser Phase entspannen sich die Muskeln, die Atmung wird ruhiger, und man kann noch relativ "
    "leicht geweckt werden. Sie nimmt etwa die Hälfte der gesamten Schlafzeit ein.",
    "Die zweite Phase, der Tiefschlaf, ist für unser Thema besonders wichtig. Im Tiefschlaf sind die Hirnströme langsam und "
    "gleichmäßig, der Blutdruck sinkt, und der Körper regeneriert sich. Wer aus dem Tiefschlaf geweckt wird, ist zunächst "
    "verwirrt und braucht einige Minuten, bis er sich orientiert. Der Tiefschlaf konzentriert sich auf die erste Hälfte der "
    "Nacht. Das bedeutet: Wer nur fünf Stunden schläft, verliert vor allem die späteren Phasen, in denen der Tiefschlaf "
    "kaum noch vorkommt, wohl aber die dritte Phase, der sogenannte REM-Schlaf.",
    "Der REM-Schlaf, die dritte Phase, trägt seinen Namen nach den schnellen Augenbewegungen, englisch rapid eye movements, "
    "die man dabei beobachten kann. In dieser Phase ist das Gehirn fast so aktiv wie im Wachzustand, während die Muskulatur "
    "nahezu vollständig erschlafft. Hier finden die meisten intensiven Träume statt. Der REM-Schlaf nimmt im Laufe der Nacht "
    "zu; die längsten REM-Phasen treten deshalb in den frühen Morgenstunden auf. Wir halten also fest: Leichtschlaf, "
    "Tiefschlaf und REM-Schlaf wechseln sich ab, und jede Phase erfüllt eine eigene Aufgabe.",
    "Damit komme ich zur ersten Untersuchung. Ein Forschungsteam aus Lübeck ließ Versuchspersonen am Abend eine Liste von "
    "Wortpaaren auswendig lernen. Eine Gruppe durfte anschließend schlafen, die andere Gruppe blieb die ganze Nacht wach. "
    "Am nächsten Morgen wurden beide Gruppen abgefragt. Das Ergebnis war eindeutig: Die Gruppe, die geschlafen hatte, "
    "erinnerte sich im Durchschnitt an mehr als doppelt so viele Wortpaare. Besonders gut war die Leistung bei den "
    "Versuchspersonen, deren Tiefschlaf in der ersten Nachthälfte ungestört geblieben war. Die Forscher schließen daraus, "
    "dass der Tiefschlaf das Faktenwissen im Gedächtnis festigt, indem neu Gelerntes vom Kurzzeitspeicher in den "
    "Langzeitspeicher übertragen wird.",
    "Die zweite Untersuchung betrifft eine andere Art des Lernens. Eine Forschungsgruppe in Tübingen ließ Studierende eine "
    "motorische Aufgabe üben, nämlich eine bestimmte Fingerfolge auf einer Tastatur. Auch hier verbesserten sich diejenigen, "
    "die anschließend geschlafen hatten, deutlich stärker als diejenigen, die tagsüber wach geblieben waren. Diesmal "
    "hing der Effekt jedoch mit dem REM-Schlaf zusammen. Während der Tiefschlaf also vor allem das Faktenwissen stabilisiert, "
    "scheint der REM-Schlaf für Fertigkeiten und für das Verknüpfen von Informationen wichtig zu sein. Beide Befunde "
    "zeigen, dass Schlaf kein Zeitverlust ist, sondern ein aktiver Teil des Lernprozesses.",
    "An dieser Stelle möchte ich einen Einwand aufgreifen, den ich in den Übungsgruppen häufig höre. Manche Studierende sagen, "
    "sie kämen mit vier oder fünf Stunden Schlaf aus und fühlten sich völlig leistungsfähig. Die Forschung sieht das kritisch. "
    "In Versuchen unterschätzen Menschen mit dauerhaftem Schlafmangel ihre Einbußen systematisch: Sie schneiden in "
    "Aufmerksamkeitstests deutlich schlechter ab, meinen aber, alles sei in Ordnung. Man spricht von einer Gewöhnung an den "
    "Mangel, nicht von einem geringeren Bedarf. Der durchschnittliche Erwachsene braucht nach den vorliegenden Daten sieben "
    "bis neun Stunden Schlaf.",
    "Eine Zwischenfrage aus dem letzten Semester lautete, ob ein kurzer Mittagsschlaf helfen könne. Die Antwort ist: ja, unter "
    "Bedingungen. Ein Nickerchen von zwanzig bis dreißig Minuten bleibt im Leichtschlaf und steigert die Aufmerksamkeit am "
    "Nachmittag, ohne dass man danach benommen ist. Schläft man dagegen länger als eine halbe Stunde, gerät man in den "
    "Tiefschlaf und fühlt sich beim Aufwachen zunächst schlechter. Für die Festigung von Faktenwissen ersetzt ein "
    "Mittagsschlaf den Nachtschlaf allerdings nicht, weil der Tiefschlaf in der ersten Nachthälfte konzentriert ist.",
    "Nun zu den Empfehlungen. Erstens: Lernen Sie nicht die ganze Nacht durch. Wer vor einer Prüfung eine Nacht opfert, "
    "verschenkt genau die Phasen, in denen das Gelernte gefestigt wird. Zweitens: Legen Sie schwierigen Stoff möglichst auf "
    "den Abend, damit der folgende Schlaf ihn verarbeiten kann, und wiederholen Sie ihn am nächsten Morgen kurz. Drittens: "
    "Achten Sie auf regelmäßige Schlafenszeiten. Ein unregelmäßiger Rhythmus stört vor allem die Tiefschlafphase. Viertens "
    "und letztens: Verzichten Sie in den Stunden vor dem Einschlafen auf helles Bildschirmlicht und auf Koffein, denn beides "
    "verzögert das Einschlafen und verkürzt den Tiefschlaf.",
    "Lassen Sie mich zusammenfassen. Schlaf besteht aus wiederkehrenden Zyklen mit Leichtschlaf, Tiefschlaf und REM-Schlaf. "
    "Der Tiefschlaf festigt Faktenwissen, der REM-Schlaf unterstützt Fertigkeiten und Verknüpfungen. Wer Prüfungen "
    "erfolgreich bestehen will, sollte deshalb den Schlaf nicht als Gegner des Lernens betrachten, sondern als seinen "
    "wichtigsten Verbündeten. Im Anschluss an die Pause werden wir uns anschauen, wie sich diese Erkenntnisse in einem "
    "Lernplan für die Prüfungswochen umsetzen lassen. Vielen Dank für Ihre Aufmerksamkeit.",
]
HV_TEXT = "\n\n".join(HV_PARAGRAPHS)

HV_CONTENT = {
    "lectureText": HV_TEXT,
    "tasks": [
        {"form": "questions", "items": [
            {"itemId": "hv_q1", "question": "Welche drei Phasen des Schlafs unterscheidet der Referent?", "maxPoints": 3,
             "requiredPoints": [
                 _pt("hv_q1_p1", "Leichtschlaf", 1, "leichtschlaf"),
                 _pt("hv_q1_p2", "Tiefschlaf", 1, "tiefschlaf"),
                 _pt("hv_q1_p3", "REM-Schlaf", 1, "rem")],
             "referenceAnswer": "Er unterscheidet den Leichtschlaf, den Tiefschlaf und den REM-Schlaf.",
             "errorfulVariant": "Er unterscheiden Leichtschlaf, Tiefschlaf und der REM-Schlaf."},
            {"itemId": "hv_q2", "question": "Welche Rolle spielt der Tiefschlaf für das Lernen?", "maxPoints": 2,
             "requiredPoints": [
                 _pt("hv_q2_p1", "Festigt Faktenwissen", 1, "faktenwissen", "fakten"),
                 _pt("hv_q2_p2", "Überträgt Gelerntes vom Kurz- in den Langzeitspeicher", 1, "langzeit")],
             "referenceAnswer": "Der Tiefschlaf festigt das Faktenwissen, indem Gelerntes in den Langzeitspeicher übertragen wird.",
             "errorfulVariant": "Tiefschlaf festigen Faktenwissen, weil Gelernt in Langzeitspeicher übertragt wird."},
        ]},
        {"form": "structure_sketch", "items": [
            {"itemId": "hv_sk", "question": "Skizzieren Sie den Aufbau des Vortrags.", "maxPoints": 4,
             "requiredPoints": [
                 _pt("hv_sk_p1", "Einleitung: Schlaf und Lernleistung", 1, "einleitung", "thema"),
                 _pt("hv_sk_p2", "Aufbau des Schlafs in Phasen", 1, "phasen", "aufbau"),
                 _pt("hv_sk_p3", "Zwei Untersuchungen", 1, "untersuchung", "studie"),
                 _pt("hv_sk_p4", "Empfehlungen für die Prüfungsvorbereitung", 1, "empfehlung")],
             "referenceAnswer": "Einleitung zum Thema; Aufbau des Schlafs in Phasen; zwei Untersuchungen; Empfehlungen.",
             "errorfulVariant": "Einleitung Thema; Aufbau Schlaf Phasen; zwei Untersuchung; Empfehlung."},
        ]},
    ],
}

# ---- TP ------------------------------------------------------------------------------------------------
TP_CONTENT = {
    "inputs": [
        {"kind": "table", "id": "i1", "caption": "Studiendauer und Studienabbruch nach Fächergruppen (fiktive Übungsdaten)",
         "rows": [["Fächergruppe", "Durchschnittliche Studiendauer (Semester)", "Abbruchquote (%)"],
                  ["Ingenieurwissenschaften", "11", "32"], ["Sprach- und Kulturwissenschaften", "10", "27"],
                  ["Rechts- und Wirtschaftswissenschaften", "9", "19"]]},
        {"kind": "quotation", "id": "i2",
         "text": "Ein Studienabbruch ist nicht immer ein Scheitern, sondern oft eine sinnvolle Neuorientierung."},
    ],
    "languageActs": ["describe", "compare", "take_position"],
    "instructions": "Beschreiben Sie die Angaben der Tabelle, vergleichen Sie die drei Fächergruppen und nehmen Sie Stellung zu "
                    "der Aussage im Zitat. Begründen Sie Ihre Meinung.",
    "wordCountApprox": 250,
    "inputRefs": ["i1", "i2"],
}

TOPICS = {"listening": "hv_sleep_learning", "reading": "lv_circular_economy", "writing": "tp_study_duration"}


def fresh(obj):
    """A deep copy so a test can break one thing without touching the shared golden content."""
    return copy.deepcopy(obj)
